version: '3.7'

services:
  web:
    build:
      context: tools/docker
    depends_on:
      - database
    ports:
      - 80:80
    env_file:
      - docker.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_DATABASE=koel
      - DB_USERNAME=koel
      - APP_DEBUG=true
    volumes:
      - .:/usr/share/koel:cached
      - music:/music

  database:
    image: mysql/mysql-server:5.7
    env_file:
      - docker.env
    environment:
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  music:
